name: simanja_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  date_picker_timeline: ^1.2.6
  excel: ^4.0.3
  file_picker: ^8.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  riverpod_annotation: ^2.3.5
  sizer: ^2.0.15
  supabase_flutter: ^2.5.7
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy-SemiBold.ttf
  uses-material-design: true
  assets:
    - assets/.env
    - assets/logo/4.png
    - assets/logo/5.png
    - assets/logo/6.png
    - assets/logo/7.png
    - assets/logo/Kelola_Inventaris_Icon.png
    - assets/logo/Kelola_Kas_Icon.png
    - assets/logo/Logo Word.png
    - assets/logo/No_Profil_Picture.png
    - assets/logo/No_Image.jpg
    - assets/logo/SiMandja-Logo.png
